server:
  port: 8081

spring:
  application:
    name: user-service

  datasource:
    url: jdbc:postgresql://localhost:5432/user_service_db
    username: rashadsuleymanov
    password: 4424

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true